main: me.KlukCZ.VIPReporter.Main
version: 1.3.5
name: VIPReporter
api-version: 1.13

commands:
  report:
    description: Reports a player
    usage: /<command>

  vipreporter:
    description: VIPReporter main command
    usage: /<command>

  checkreport:
    description: Checks players report log
    usage: /<command>

permissions:
  vipreporter.admin:
    description: Admin permission
    default: op